export default function Home() {
  return (
    <div className='flex flex-col items-center justify-center text-[#fff]'>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
      <span>helle</span>
    </div>
  );
}
